# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='include/a/infra/log/level.proto',
  package='a.log',
  serialized_pb='\n\x1finclude/a/infra/log/level.proto\x12\x05\x61.log\"\xd5\x01\n\x08LevelGpb\"\xc8\x01\n\x05Value\x12\x11\n\rkInfinitLevel\x10\x00\x12\x0e\n\nkEmergency\x10\n\x12\n\n\x06kAlert\x10\x0e\x12\r\n\tkCritical\x10\x12\x12\n\n\x06kError\x10\x16\x12\x0c\n\x08kWarning\x10\x1a\x12\x0b\n\x07kNotice\x10\x1e\x12\t\n\x05kInfo\x10\"\x12\x0b\n\x07kDebug1\x10&\x12\x0b\n\x07kDebug2\x10*\x12\x0b\n\x07kDebug3\x10.\x12\x0b\n\x07kDebug4\x10\x32\x12\x0b\n\x07kDebug5\x10\x36\x12\x0e\n\nkLastLevel\x10\x36\"P\n\rLevelStatsGpb\x12\x0c\n\x04sent\x18\x01 \x03(\x03\x12\x10\n\x08\x66iltered\x18\x02 \x03(\x03\x12\x0f\n\x07\x64ropped\x18\x03 \x03(\x03\x12\x0e\n\x06\x66\x61iled\x18\x04 \x03(\x03\"V\n\x13SingleLevelStatsGpb\x12\x0c\n\x04sent\x18\x01 \x01(\x03\x12\x10\n\x08\x66iltered\x18\x02 \x01(\x03\x12\x0f\n\x07\x64ropped\x18\x03 \x01(\x03\x12\x0e\n\x06\x66\x61iled\x18\x04 \x01(\x03')



_LEVELGPB_VALUE = descriptor.EnumDescriptor(
  name='Value',
  full_name='a.log.LevelGpb.Value',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='kInfinitLevel', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kEmergency', index=1, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kAlert', index=2, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kCritical', index=3, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kError', index=4, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kWarning', index=5, number=26,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kNotice', index=6, number=30,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kInfo', index=7, number=34,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kDebug1', index=8, number=38,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kDebug2', index=9, number=42,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kDebug3', index=10, number=46,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kDebug4', index=11, number=50,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kDebug5', index=12, number=54,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kLastLevel', index=13, number=54,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=56,
  serialized_end=256,
)


_LEVELGPB = descriptor.Descriptor(
  name='LevelGpb',
  full_name='a.log.LevelGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LEVELGPB_VALUE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=256,
)


_LEVELSTATSGPB = descriptor.Descriptor(
  name='LevelStatsGpb',
  full_name='a.log.LevelStatsGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sent', full_name='a.log.LevelStatsGpb.sent', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filtered', full_name='a.log.LevelStatsGpb.filtered', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dropped', full_name='a.log.LevelStatsGpb.dropped', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='failed', full_name='a.log.LevelStatsGpb.failed', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=258,
  serialized_end=338,
)


_SINGLELEVELSTATSGPB = descriptor.Descriptor(
  name='SingleLevelStatsGpb',
  full_name='a.log.SingleLevelStatsGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sent', full_name='a.log.SingleLevelStatsGpb.sent', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filtered', full_name='a.log.SingleLevelStatsGpb.filtered', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dropped', full_name='a.log.SingleLevelStatsGpb.dropped', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='failed', full_name='a.log.SingleLevelStatsGpb.failed', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=340,
  serialized_end=426,
)


_LEVELGPB_VALUE.containing_type = _LEVELGPB;

class LevelGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEVELGPB
  
  # @@protoc_insertion_point(class_scope:a.log.LevelGpb)

class LevelStatsGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEVELSTATSGPB
  
  # @@protoc_insertion_point(class_scope:a.log.LevelStatsGpb)

class SingleLevelStatsGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SINGLELEVELSTATSGPB
  
  # @@protoc_insertion_point(class_scope:a.log.SingleLevelStatsGpb)

# @@protoc_insertion_point(module_scope)
