/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojectui;

import Utils.ClosableTab;
import finalprojectui.Entities.Pair;
import finalprojectui.Reports.ItagStatisticsReport.ItagStatisticsReportPanel;
import finalprojectui.Reports.ReqParamStatisticsReport.ReqParamStatisticsReportPanel;
import finalprojectui.Reports.UserAgentStatisticsReport.UserAgentStatisticsReportPanel;
import java.awt.Dialog;
import java.awt.Image;
import java.util.Vector;
import javax.swing.*;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author dell
 */
public class MainPanel extends javax.swing.JPanel {
    private ReportType lastSelectedReport;
    private int _numberOfItagStatisticsReport;
    private int _numberOfReqParamStatisticsReport;
    private int _numberOfUserAgentStatisticsReport;
    
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        _numberOfItagStatisticsReport=-1;
        _numberOfReqParamStatisticsReport=-1;
        _numberOfUserAgentStatisticsReport=-1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportsTabPanel = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportsTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportsTabPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadCoalFile(String filePath)
    {
        //TODO: need to implelent
    
    }
    public void openNewReportTab(Vector<Pair<Integer,String>> coalFiles)
    {
        int count=0;
        JPanel panelToAdd=null;
        if(lastSelectedReport.equalsName(ReportType.ItagStatisticsReport.toString()))
        {
            _numberOfItagStatisticsReport++;
            count=_numberOfItagStatisticsReport;
            panelToAdd=new ItagStatisticsReportPanel(coalFiles);
        }
        else if(lastSelectedReport.equalsName(ReportType.ReqParamStatisticsReport.toString()))
        {
            _numberOfReqParamStatisticsReport++;
            count=_numberOfReqParamStatisticsReport;
            panelToAdd=new ReqParamStatisticsReportPanel(coalFiles);
        }
        else if(lastSelectedReport.equalsName(ReportType.UserAgentStatisticsReport.toString()))
        {
            _numberOfUserAgentStatisticsReport++;
            count=_numberOfUserAgentStatisticsReport;
            panelToAdd=new UserAgentStatisticsReportPanel(coalFiles);
        }
        if(count==0)
        {
            reportsTabPanel.add(lastSelectedReport.name(), panelToAdd);
        }
        else
        {
            reportsTabPanel.add(lastSelectedReport.name()+"("+count+")", panelToAdd);
        }
        
        reportsTabPanel.setSelectedIndex(reportsTabPanel.getTabCount()-1);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane reportsTabPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lastSelectedReport
     */
    public ReportType getLastSelectedReport() {
        return lastSelectedReport;
    }

    /**
     * @param lastSelectedReport the lastSelectedReport to set
     */
    public void setLastSelectedReport(ReportType lastSelectedReport) {
        this.lastSelectedReport = lastSelectedReport;
    }
}
