# This file contains Exceptions generated byGPB  classes

class GPBChainException(Exception):
    '''General exception during chain read operation'''
    pass

class InvalidCRCException(GPBChainException):
    def __init__(self,expectedCRC,actualCRC):
        self.expectedCRC = expectedCRC
        self.actualCRC = actualCRC
    def __str__(self):
        return "ERROR: CRC doesn't match (expected 0x%x actual 0x%x)" % (self.expectedCRC, self.actualCRC)


class UnknownGPBMessageException(GPBChainException):
    def __init__(self, descriptorNameHash):
        self.descriptorNameHash = descriptorNameHash
    def __str__(self):
        return "ERROR: GPB Message is unknown (DNH 0x%x is not registered in factory)" % self.descriptorNameHash

class NotCompleteMessageException(GPBChainException):
    def __init__(self, length):
        self.length = length
    def __str__ (self):
        return "ERROR: Failed to read complete message from stream, required length is %d" % self.length

