# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='infra/config/ut/example.proto',
  package='a.config.ut',
  serialized_pb='\n\x1dinfra/config/ut/example.proto\x12\x0b\x61.config.ut\x1a)include/a/infra/config/config_types.proto\x1a&include/a/infra/prov/definitions.proto\">\n\x15\x45xampleType1ConfigGpb\x12\x10\n\x05\x61ttr1\x18\x01 \x01(\x03:\x01\x37\x12\x13\n\x05\x61ttr2\x18\x02 \x01(\t:\x04lala\"l\n\x15\x45xampleType2ConfigGpb\x12\x10\n\x05\x61ttr3\x18\x01 \x01(\x03:\x01\x37\x12\r\n\x05stuff\x18\x02 \x03(\x03\x12\x32\n\x10stuffListControl\x18\x03 \x01(\x0b\x32\x18.a.config.ListControlGpb\"\'\n\x18\x45xampleType4KeyConfigGpb\x12\x0b\n\x03key\x18\x01 \x01(\x05\":\n\x15\x45xampleType4ConfigGpb\x12\r\n\x05\x61ttr5\x18\x01 \x01(\x08\x12\x12\n\x05\x61ttr6\x18\x02 \x01(\t:\x03\x64\x65\x66')




_EXAMPLETYPE1CONFIGGPB = descriptor.Descriptor(
  name='ExampleType1ConfigGpb',
  full_name='a.config.ut.ExampleType1ConfigGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='attr1', full_name='a.config.ut.ExampleType1ConfigGpb.attr1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=7,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attr2', full_name='a.config.ut.ExampleType1ConfigGpb.attr2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("lala", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=191,
)


_EXAMPLETYPE2CONFIGGPB = descriptor.Descriptor(
  name='ExampleType2ConfigGpb',
  full_name='a.config.ut.ExampleType2ConfigGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='attr3', full_name='a.config.ut.ExampleType2ConfigGpb.attr3', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=7,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stuff', full_name='a.config.ut.ExampleType2ConfigGpb.stuff', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stuffListControl', full_name='a.config.ut.ExampleType2ConfigGpb.stuffListControl', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=193,
  serialized_end=301,
)


_EXAMPLETYPE4KEYCONFIGGPB = descriptor.Descriptor(
  name='ExampleType4KeyConfigGpb',
  full_name='a.config.ut.ExampleType4KeyConfigGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='a.config.ut.ExampleType4KeyConfigGpb.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=303,
  serialized_end=342,
)


_EXAMPLETYPE4CONFIGGPB = descriptor.Descriptor(
  name='ExampleType4ConfigGpb',
  full_name='a.config.ut.ExampleType4ConfigGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='attr5', full_name='a.config.ut.ExampleType4ConfigGpb.attr5', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attr6', full_name='a.config.ut.ExampleType4ConfigGpb.attr6', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("def", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=344,
  serialized_end=402,
)

import include.a.infra.config.config_types_pb2
import include.a.infra.prov.definitions_pb2

_EXAMPLETYPE2CONFIGGPB.fields_by_name['stuffListControl'].message_type = include.a.infra.config.config_types_pb2._LISTCONTROLGPB

class ExampleType1ConfigGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXAMPLETYPE1CONFIGGPB
  
  # @@protoc_insertion_point(class_scope:a.config.ut.ExampleType1ConfigGpb)

class ExampleType2ConfigGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXAMPLETYPE2CONFIGGPB
  
  # @@protoc_insertion_point(class_scope:a.config.ut.ExampleType2ConfigGpb)

class ExampleType4KeyConfigGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXAMPLETYPE4KEYCONFIGGPB
  
  # @@protoc_insertion_point(class_scope:a.config.ut.ExampleType4KeyConfigGpb)

class ExampleType4ConfigGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXAMPLETYPE4CONFIGGPB
  
  # @@protoc_insertion_point(class_scope:a.config.ut.ExampleType4ConfigGpb)

# @@protoc_insertion_point(module_scope)
