/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojectui.Reports.ItagStatisticsReport;

import finalprojectui.Entities.Pair;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author dell
 */
public class ItagStatisticsReportReaultsPanel extends javax.swing.JPanel {

    /**
     * Creates new form
     * RequestsPercentagePerHeaderReportParametersPanelReaultsPanel
     */
    public ItagStatisticsReportReaultsPanel() {
        initComponents();
        initTable();
    }
    
    private void initTable()
    {
        ItagStatisticsReportLoader loader=new ItagStatisticsReportLoader(null);
        loader.load();
        Vector<Pair<Integer,Double>> count=loader.getCountResults();
        Vector<Pair<Integer,Double>> trans=loader.getTransResults();
        Vector<Pair<Integer,Double>> bytes=loader.getBytesResults();
        
        String[] columnNames={"Distinct item values","Count","% Transactions", "% Bytes"};
        TableModel model=resTable.getModel();
        DefaultTableModel newModel=new DefaultTableModel(columnNames,count.size());
        for(int i=0; i<count.size(); i++)
        {
            newModel.setValueAt(count.get(i).getKey(), i, 0);
            newModel.setValueAt(count.get(i).getValue(), i, 1);
            newModel.setValueAt(trans.get(i).getValue(), i, 2);
            newModel.setValueAt(bytes.get(i).getValue(), i, 3);
        }
        
        resTable.setModel(newModel);
    }
    
    private void initGraph()
    {
        // This will create the dataset 
        PieDataset dataset = createDataset();
        // based on the dataset we create the chart
        JFreeChart chart = createChart(dataset, "Title");
        // we put the chart into a panel
        ChartPanel chartPanel = new ChartPanel(chart);
        // default size
        chartPanel.setPreferredSize(new java.awt.Dimension(200, 270));
        // add it to our application
        this.add(chartPanel);
    }
    /**
     * Creates a sample dataset 
     */

    private  PieDataset createDataset() {
        DefaultPieDataset result = new DefaultPieDataset();
        result.setValue("Linux", 29);
        result.setValue("Mac", 20);
        result.setValue("Windows", 51);
        return result;
        
    }
    
    
/**
     * Creates a chart
     */

    private JFreeChart createChart(PieDataset dataset, String title) {
        
        JFreeChart chart = ChartFactory.createPieChart3D(title,          // chart title
            dataset,                // data
            true,                   // include legend
            true,
            false);

        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        return chart;
        
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resTable = new javax.swing.JTable();

        resTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Distinct item values", "Count", "% Transactions", "% Bytes4"
            }
        ));
        jScrollPane1.setViewportView(resTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resTable;
    // End of variables declaration//GEN-END:variables
}
