# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='include/a/content/tracking/delivery/delivery_tracking.proto',
  package='a.content.tracking.delivery',
  serialized_pb='\n;include/a/content/tracking/delivery/delivery_tracking.proto\x12\x1b\x61.content.tracking.delivery\x1a&include/a/infra/prov/definitions.proto\"~\n\x16\x44\x65liveryTrackingKeyGpb\x12\x18\n\x10originalClientIp\x18\x01 \x01(\t\x12 \n\x18\x64\x65liveryTrackingPlayerId\x18\x02 \x01(\t\x12(\n deliveryTrackingSignatureGroupId\x18\x03 \x01(\t\"\xd2\x02\n\x18\x44\x65liveryTrackingDeltaGpb\x12R\n\tdeltaLine\x18\x01 \x03(\x0b\x32?.a.content.tracking.delivery.DeliveryTrackingDeltaGpb.DeltaLine\x1a\xad\x01\n\tDeltaLine\x12\x0e\n\x06seqNum\x18\x01 \x01(\x03\x12N\n\x03\x63md\x18\x02 \x01(\x0e\x32\x41.a.content.tracking.delivery.DeliveryTrackingDeltaGpb.CommandType\x12@\n\x03key\x18\x03 \x01(\x0b\x32\x33.a.content.tracking.delivery.DeliveryTrackingKeyGpb\"2\n\x0b\x43ommandType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\x0e\n\nDELETE_ALL\x10\x02')



_DELIVERYTRACKINGDELTAGPB_COMMANDTYPE = descriptor.EnumDescriptor(
  name='CommandType',
  full_name='a.content.tracking.delivery.DeliveryTrackingDeltaGpb.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DELETE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DELETE_ALL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=549,
  serialized_end=599,
)


_DELIVERYTRACKINGKEYGPB = descriptor.Descriptor(
  name='DeliveryTrackingKeyGpb',
  full_name='a.content.tracking.delivery.DeliveryTrackingKeyGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='originalClientIp', full_name='a.content.tracking.delivery.DeliveryTrackingKeyGpb.originalClientIp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deliveryTrackingPlayerId', full_name='a.content.tracking.delivery.DeliveryTrackingKeyGpb.deliveryTrackingPlayerId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deliveryTrackingSignatureGroupId', full_name='a.content.tracking.delivery.DeliveryTrackingKeyGpb.deliveryTrackingSignatureGroupId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=132,
  serialized_end=258,
)


_DELIVERYTRACKINGDELTAGPB_DELTALINE = descriptor.Descriptor(
  name='DeltaLine',
  full_name='a.content.tracking.delivery.DeliveryTrackingDeltaGpb.DeltaLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='seqNum', full_name='a.content.tracking.delivery.DeliveryTrackingDeltaGpb.DeltaLine.seqNum', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cmd', full_name='a.content.tracking.delivery.DeliveryTrackingDeltaGpb.DeltaLine.cmd', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key', full_name='a.content.tracking.delivery.DeliveryTrackingDeltaGpb.DeltaLine.key', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=374,
  serialized_end=547,
)

_DELIVERYTRACKINGDELTAGPB = descriptor.Descriptor(
  name='DeliveryTrackingDeltaGpb',
  full_name='a.content.tracking.delivery.DeliveryTrackingDeltaGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='deltaLine', full_name='a.content.tracking.delivery.DeliveryTrackingDeltaGpb.deltaLine', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DELIVERYTRACKINGDELTAGPB_DELTALINE, ],
  enum_types=[
    _DELIVERYTRACKINGDELTAGPB_COMMANDTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=261,
  serialized_end=599,
)

import include.a.infra.prov.definitions_pb2

_DELIVERYTRACKINGDELTAGPB_DELTALINE.fields_by_name['cmd'].enum_type = _DELIVERYTRACKINGDELTAGPB_COMMANDTYPE
_DELIVERYTRACKINGDELTAGPB_DELTALINE.fields_by_name['key'].message_type = _DELIVERYTRACKINGKEYGPB
_DELIVERYTRACKINGDELTAGPB_DELTALINE.containing_type = _DELIVERYTRACKINGDELTAGPB;
_DELIVERYTRACKINGDELTAGPB.fields_by_name['deltaLine'].message_type = _DELIVERYTRACKINGDELTAGPB_DELTALINE
_DELIVERYTRACKINGDELTAGPB_COMMANDTYPE.containing_type = _DELIVERYTRACKINGDELTAGPB;

class DeliveryTrackingKeyGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELIVERYTRACKINGKEYGPB
  
  # @@protoc_insertion_point(class_scope:a.content.tracking.delivery.DeliveryTrackingKeyGpb)

class DeliveryTrackingDeltaGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class DeltaLine(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DELIVERYTRACKINGDELTAGPB_DELTALINE
    
    # @@protoc_insertion_point(class_scope:a.content.tracking.delivery.DeliveryTrackingDeltaGpb.DeltaLine)
  DESCRIPTOR = _DELIVERYTRACKINGDELTAGPB
  
  # @@protoc_insertion_point(class_scope:a.content.tracking.delivery.DeliveryTrackingDeltaGpb)

# @@protoc_insertion_point(module_scope)
