# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='include/a/infra/ipc/services/shell.proto',
  package='a.ipc',
  serialized_pb='\n(include/a/infra/ipc/services/shell.proto\x12\x05\x61.ipc\x1a&include/a/infra/prov/definitions.proto\x1a\x1finclude/a/infra/ipc/shell.proto\"\x9c\x01\n\x10IpcServerInfoGpb\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.a.ipc.IpcServerInfoGpb.Type\x12$\n\x08services\x18\x03 \x01(\x0b\x32\x12.a.ipc.ServicesGpb\"(\n\x04Type\x12\x0f\n\x0bkHipcServer\x10\x00\x12\x0f\n\x0bkPipcServer\x10\x01\"O\n\x11IpcServersInfoGpb\x12\x13\n\x0bnoOfServers\x18\x01 \x01(\x03\x12%\n\x04info\x18\x02 \x03(\x0b\x32\x17.a.ipc.IpcServerInfoGpb\"s\n\x14getIpcServersInfoGpb\x12\x1b\n\x02in\x18\x01 \x01(\x0b\x32\x0f.a.prov.NullGpb\x12%\n\x03out\x18\x02 \x01(\x0b\x32\x18.a.ipc.IpcServersInfoGpb:\x17\x8a\xb5\x18\x13List of IPC Servers')



_IPCSERVERINFOGPB_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='a.ipc.IpcServerInfoGpb.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='kHipcServer', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='kPipcServer', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=241,
  serialized_end=281,
)


_IPCSERVERINFOGPB = descriptor.Descriptor(
  name='IpcServerInfoGpb',
  full_name='a.ipc.IpcServerInfoGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='a.ipc.IpcServerInfoGpb.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='a.ipc.IpcServerInfoGpb.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='services', full_name='a.ipc.IpcServerInfoGpb.services', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IPCSERVERINFOGPB_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=125,
  serialized_end=281,
)


_IPCSERVERSINFOGPB = descriptor.Descriptor(
  name='IpcServersInfoGpb',
  full_name='a.ipc.IpcServersInfoGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='noOfServers', full_name='a.ipc.IpcServersInfoGpb.noOfServers', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='info', full_name='a.ipc.IpcServersInfoGpb.info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=283,
  serialized_end=362,
)


_GETIPCSERVERSINFOGPB = descriptor.Descriptor(
  name='getIpcServersInfoGpb',
  full_name='a.ipc.getIpcServersInfoGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='in', full_name='a.ipc.getIpcServersInfoGpb.in', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='out', full_name='a.ipc.getIpcServersInfoGpb.out', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=descriptor._ParseOptions(descriptor_pb2.MessageOptions(), '\212\265\030\023List of IPC Servers'),
  is_extendable=False,
  extension_ranges=[],
  serialized_start=364,
  serialized_end=479,
)

import include.a.infra.prov.definitions_pb2
import include.a.infra.ipc.shell_pb2

_IPCSERVERINFOGPB.fields_by_name['type'].enum_type = _IPCSERVERINFOGPB_TYPE
_IPCSERVERINFOGPB.fields_by_name['services'].message_type = include.a.infra.ipc.shell_pb2._SERVICESGPB
_IPCSERVERINFOGPB_TYPE.containing_type = _IPCSERVERINFOGPB;
_IPCSERVERSINFOGPB.fields_by_name['info'].message_type = _IPCSERVERINFOGPB
_GETIPCSERVERSINFOGPB.fields_by_name['in'].message_type = include.a.infra.prov.definitions_pb2._NULLGPB
_GETIPCSERVERSINFOGPB.fields_by_name['out'].message_type = _IPCSERVERSINFOGPB

class IpcServerInfoGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IPCSERVERINFOGPB
  
  # @@protoc_insertion_point(class_scope:a.ipc.IpcServerInfoGpb)

class IpcServersInfoGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IPCSERVERSINFOGPB
  
  # @@protoc_insertion_point(class_scope:a.ipc.IpcServersInfoGpb)

class getIpcServersInfoGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETIPCSERVERSINFOGPB
  
  # @@protoc_insertion_point(class_scope:a.ipc.getIpcServersInfoGpb)

# @@protoc_insertion_point(module_scope)
