
import os.path
#import utils
import a.sys.sys_web.server.log

# === DataProvider ====================================================================================================

class DataProvider():
    def __init__(self, apiLogger = None, mainLogger = None):
        self.apiLogger  = apiLogger  if apiLogger  is not None else a.sys.sys_web.server.log.NullLogger()
        self.mainLogger = mainLogger if mainLogger is not None else a.sys.sys_web.server.log.NullLogger()

   # --- site list
    def _addSite(self, entries, name, icon = None, bitRateSupported=False):

        entry = {}

        entry['siteName'] = name
        entry['siteId']   = name.lower()

        if icon is not None:
            entry['siteIcon'] = os.path.join("site", "icons", icon)

        reports = { 'bitRate': bitRateSupported }
        entry['reports'] = reports
        entries.append(entry)

    def siteList(self, clientListVersion ):

        # List version - must be incremented when ever something is changed here 
        LIST_VERSION = 7

        result = { }
        result['listVersion'] = LIST_VERSION
    
        # add entries only if client has different version
        if clientListVersion != LIST_VERSION:
            entries = []   
            self._addSite(entries, name = "Akamaihd.net",    icon="akamai.png")
            self._addSite(entries, name = "Amazon.com",      icon="amazon.png")
            self._addSite(entries, name = "Apple.com",       icon="apple.png")
            self._addSite(entries, name = "Bbc.co.uk",       icon="bbc.png")
            self._addSite(entries, name = "BBC",             icon="bbc.png")
            self._addSite(entries, name = "BBC-Live",        icon="bbc.png")
            self._addSite(entries, name = "DailyMotion.com", icon="dailymotion.png")
            self._addSite(entries, name = "eurosport.com",   icon="eurosport.png")
            self._addSite(entries, name = "Facebook.com",    icon="facebook.png")
            self._addSite(entries, name = "Fox.com",         icon="fox.png")
            self._addSite(entries, name = "GoogleVideo.com", icon="googlevideo.png")
            self._addSite(entries, name = "Level3.net",      icon="level3.png")
            self._addSite(entries, name = "Lovefilm.com",    icon="lovefilm.png")
            self._addSite(entries, name = "Megaupload.com",  icon="megaupload.png")
            self._addSite(entries, name = "Megavideo.com",   icon="megavideo.png")
            self._addSite(entries, name = "Netflix.com",     icon="netflix.png", bitRateSupported=True)
            self._addSite(entries, name = "Pornhub.com",     icon="pornhub.png")
            self._addSite(entries, name = "sky.com",         icon="sky.png")
            self._addSite(entries, name = "Sky",             icon="sky.png")
            self._addSite(entries, name = "Sky-Live",        icon="sky.png")
            self._addSite(entries, name = "Skyanywhere.com", icon="skyanywhere.png")
            self._addSite(entries, name = "Vevo.com",        icon="vevo.png" )
            self._addSite(entries, name = "vimeo.com",       icon="vimeo.png" )
            self._addSite(entries, name = "Vudu.com",        icon="vudu.png")
            self._addSite(entries, name = "Xvideos.com",     icon="xvideos.png",bitRateSupported=True)
            self._addSite(entries, name = "Youporn.com",     icon="youporn.png", bitRateSupported=True)
            self._addSite(entries, name = "YouTube.com",     icon="youtube.png", bitRateSupported=True)
            self._addSite(entries, name = "4tube.com",       icon="4tube.com.png")
            self._addSite(entries, name = "Adinterax.com",   icon="adinterax.com.png")
            self._addSite(entries, name = "Alarab.net",      icon="alarab.net.png")
            self._addSite(entries, name = "Alphaporno.com",  icon="alphaporno.com.png")
            self._addSite(entries, name = "Applicaster.com", icon="applicaster.com.png")
            self._addSite(entries, name = "Blinkx.com",      icon="blinkx.com-16.png")
            self._addSite(entries, name = "Blip.tv",         icon="blip.tv.png")
            self._addSite(entries, name = "Cctv.com",        icon="cctv.com.png")
            self._addSite(entries, name = "Datalock.ru",     icon="datalock.ru.png")
            self._addSite(entries, name = "Dumpert.nl",      icon="dumpert-16.png")
            self._addSite(entries, name = "Empflix.com",     icon="empflix.png")
            self._addSite(entries, name = "Eroprofile.com",  icon="eroprofile.com.png")
            self._addSite(entries, name = "Fbcdn.net",       icon="fbcdn.net.png")
            self._addSite(entries, name = "Fc2.com",         icon="fc2.com.png", bitRateSupported=True)
            self._addSite(entries, name = "Fileflyer.com",   icon="fileflyer-16.png")
            self._addSite(entries, name = "Filmix.net",      icon="filmix.net.png")
            self._addSite(entries, name = "Halowaypoint.com",icon="halo.xbox.com-16.png")
            self._addSite(entries, name = "Hardsextube.com", icon="hardsextube-16.png")
            self._addSite(entries, name = "Hkedcity.net",    icon="hkedcity.net-16.png")
            self._addSite(entries, name = "Igru-film.net",   icon="igru-film.net.png")
            self._addSite(entries, name = "Iraginzburg.com", icon="iraginzburg.png")
            self._addSite(entries, name = "Itv.com",         icon="itv.com.png")
            self._addSite(entries, name = "Jet-stream.nl",   icon="jet-stream.nl-16.png")
            self._addSite(entries, name = "Justin.tv",       icon="justin.tv-16.png")
            self._addSite(entries, name = "Kino-dom.tv",     icon="kino-dom.tv.png")
            self._addSite(entries, name = "Llnwd.net",       icon="llnwd.net.png")
            self._addSite(entries, name = "Loadup.ru",       icon="loadup.ru.png")
            self._addSite(entries, name = "Mail.ru",         icon="img.mail.ru.png")
            self._addSite(entries, name = "Media-imdb.com",  icon="media-imdb.com-16.png")
            self._addSite(entries, name = "Movshare.net",    icon="movshare.png")
            self._addSite(entries, name = "Muzu.tv",         icon="muzu.tv.png")
            self._addSite(entries, name = "My-hit.ru",       icon="my-hit.ru-16.png")
            self._addSite(entries, name = "Nicovideo.jp",    icon="nicovideo.jp.png", bitRateSupported=True)
            self._addSite(entries, name = "Novamov.com",     icon="novamov.png")
            self._addSite(entries, name = "One.co.il",       icon="one.co.il-16.png")
            self._addSite(entries, name = "Pogoplug.com",    icon="pogoplug.com.png")
            self._addSite(entries, name = "Porn.com",        icon="porn.com.png")
            self._addSite(entries, name = "Putlocker.com",   icon="putlocker.png")
            self._addSite(entries, name = "Rawtube.com",     icon="rawtube.png")
            self._addSite(entries, name = "Rtl.nl",          icon="rtl.nl.png")
            self._addSite(entries, name = "Sapo.pt",         icon="sapo-16.png")
            self._addSite(entries, name = "Sdarot.be",       icon="sdarot.be.png")
            self._addSite(entries, name = "Skyfire.com",     icon="skyfire.png")
            self._addSite(entries, name = "Skyviewworld.com",icon="skyviewworld-16.png")
            self._addSite(entries, name = "Sockshare.com",   icon="sockshare.png")
            self._addSite(entries, name = "Stepashka.com",   icon="stepashka.png")
            self._addSite(entries, name = "Telenet-ops.be",  icon="telenet-16.png")
            self._addSite(entries, name = "Thisav.com",      icon="thisav.com.png")
            self._addSite(entries, name = "Tnaflix.com",     icon="tnaflix.png")
            self._addSite(entries, name = "Tube8.com",       icon="tube8-16.png")
            self._addSite(entries, name = "Uloz.to",         icon="uloz.to.png")
            self._addSite(entries, name = "Videobam.com",    icon="videobam.com.png")
            self._addSite(entries, name = "Videoweed.es",    icon="videoweed.es.png")
            self._addSite(entries, name = "Vk.com",          icon="vk.com.png")
            self._addSite(entries, name = "Vkontakte.ru",    icon="vk.com.png")
            self._addSite(entries, name = "Vmma.be",         icon="vmma.be-16.png")
            self._addSite(entries, name = "Xbox.com",        icon="xbox.com-16.png")
            self._addSite(entries, name = "Xboxlive.com",    icon="xbox.com-16.png")
            self._addSite(entries, name = "Xfinity.com",     icon="xfinitytv.png")
            self._addSite(entries, name = "Xtube.com",       icon="xtube.png")
            self._addSite(entries, name = "Yandex.net",      icon="yandex.ru.png")
            self._addSite(entries, name = "Yimg.com",        icon="yimg.com.png")
            self._addSite(entries, name = "Youjizz.com",     icon="youjizz-16.png")
            self._addSite(entries, name = "Zune.net",        icon="zune.net-16.png")
            self._addSite(entries, name = "5min.com",        icon="5min.png")
            self._addSite(entries, name = "abc.com",         icon="abc.com.png")
            self._addSite(entries, name = "advection.net",   icon="advection.net.png")
            self._addSite(entries, name = "espn.com",        icon="espn.go.png")
            self._addSite(entries, name = "espnradio.com",   icon="espn.go.png")
            self._addSite(entries, name = "foxnews.com",     icon="foxnews.com.png")
            self._addSite(entries, name = "gbtv.com",        icon="gbtv.com.png")
            self._addSite(entries, name = "hudl.com",        icon="hudl.com.png")
            self._addSite(entries, name = "hulu.com",        icon="hulu.com.png", bitRateSupported=True)
            self._addSite(entries, name = "kinklive.com",    icon="kinklive.con.png")
            self._addSite(entries, name = "membercontentcenter.com",     icon="memberconnectcenter.com.png")
            self._addSite(entries, name = "mozilla.net",     icon="mozila.org.png")
            self._addSite(entries, name = "streamguys.net",  icon="streamguys.com.png")
            self._addSite(entries, name = "tumblr.com",      icon="tumblr.com.png")

            # version 3
            self._addSite(entries, name = "Cloudfront.net",  icon="cloudfront.png")
            self._addSite(entries, name = "Comcast.net",     icon="comcast.png")
            self._addSite(entries, name = "Edgestream.com",  icon="edgestream.png")
            self._addSite(entries, name = "Edgesuite.net",   icon="akamai.png")
            self._addSite(entries, name = "KylinTV.net",     icon="kylintv.png")
            self._addSite(entries, name = "Mevio.com",       icon="mevio.png")
            self._addSite(entries, name = "Msecnd.net",      icon="microsoft.png")
            self._addSite(entries, name = "NeuLion.com",     icon="neulion.png")
            self._addSite(entries, name = "NBCSports.com",   icon="nbc.png")
            self._addSite(entries, name = "playstation.net", icon="playstation.png")
            self._addSite(entries, name = "Redtubefiles.com",icon="redtube.png")
            self._addSite(entries, name = "Turner.com",      icon="turner.png")
            self._addSite(entries, name = "Videobox.com",    icon="videobox.png")

            # version 4
            self._addSite(entries, name = "amazonaws.com",   icon="amazon.png")
            self._addSite(entries, name = "nflixvideo.net",  icon="netflix.png")
            self._addSite(entries, name = "nflximg.com:80",  icon="netflix.png")
            self._addSite(entries, name = "nflxvideo.net",   icon="netflix.png")
            self._addSite(entries, name = "dmcdn.net",       icon="dailymotion.png")
            self._addSite(entries, name = "hulu.jp",         icon="hulu.com.png", bitRateSupported=True)
            self._addSite(entries, name = "queen8.com",      icon="apple.png")

            self._addSite(entries, name = "10musume.com",    icon="10musume.com.png")
            self._addSite(entries, name = "1internet.tv",    icon="1internet.tv.png")
            self._addSite(entries, name = "1pondo.tv",       icon="1pondo.tv.png")
            self._addSite(entries, name = "977music.com",    icon="977music.com.png")
            self._addSite(entries, name = "abbywinters.com", icon="abbywinters.com.png")
            self._addSite(entries, name = "archive.org",     icon="archive.org.png")
            self._addSite(entries, name = "asg.to",          icon="asg.to.png")
            self._addSite(entries, name = "atitesting.com",  icon="atitesting.com.png")
            self._addSite(entries, name = "bitgravity.com",  icon="bitgravity.com.png")
            self._addSite(entries, name = "c4assets.com",    icon="c4assets.com.png")
            self._addSite(entries, name = "caribbeancom.com",icon="caribbeancom.com.png")
            self._addSite(entries, name = "daum.net",        icon="daum.net.png")
            self._addSite(entries, name = "digitalconcerthall.com", icon="digitalconcerthall.com.png")
            self._addSite(entries, name = "dmm.co.jp",       icon="dmm.co.jp.png")
            self._addSite(entries, name = "dropmark.com",    icon="dropmark.com.png")
            self._addSite(entries, name = "filebox.com",     icon="filebox.com.png")
            self._addSite(entries, name = "godvine.com",     icon="godvine.com.png")
            self._addSite(entries, name = "hikaritv.net",    icon="hikaritv.net.png")
            self._addSite(entries, name = "istreamplanet.com", icon="istreamplanet.com.png")
            self._addSite(entries, name = "jizzhut.com",     icon="jizzhut.com.png")
            self._addSite(entries, name = "livestream.com",  icon="livestream.com.png")
            self._addSite(entries, name = "livetube.cc",     icon="livetube.cc.png")
            self._addSite(entries, name = "mgstage.com",     icon="mgstage.com.png")
            self._addSite(entries, name = "mlb.com",         icon="mlb.com.png")
            self._addSite(entries, name = "msn.com",         icon="msn.com.png")
            self._addSite(entries, name = "ncaa.com",        icon="ncaa.com.png")
            self._addSite(entries, name = "nextmedia.com",   icon="nextmedia.com.png")
            self._addSite(entries, name = "omroep.nl",       icon="omroep.nl.png")
            self._addSite(entries, name = "pacopacomama.com",icon="pacopacomama.com.png")
            self._addSite(entries, name = "para.cl",         icon="para.cl.png")
            self._addSite(entries, name = "pornerbros.com",  icon="pornerbros.com.png")
            self._addSite(entries, name = "qq.com",          icon="qq.com.png")
            self._addSite(entries, name = "realitykings.com",icon="realitykings.com.png")
            self._addSite(entries, name = "realitylapse.com",icon="realitylapse.com.png")
            self._addSite(entries, name = "uplynk.com",      icon="uplynk.com.png")
            self._addSite(entries, name = "veoh.com",        icon="veoh.com.png")
            self._addSite(entries, name = "worldnow.com",    icon="worldnow.com.png")
            self._addSite(entries, name = "x-art.com",       icon="x-art.com.png")
            self._addSite(entries, name = "zero-animation.net", icon="zero-animation.net.png")

            # version 5
            self._addSite(entries, name = "hbogo.com",      icon="hbogo.com.png")
            self._addSite(entries, name = "london2012.com", icon="london2012.com.png")


            # version 6
            # live signatures - same icon as vod
            self._addSite(entries, name = "youtube.com-live", icon="youtube.png")
            self._addSite(entries, name = "svt.se-live", icon="svt.se.png")
            self._addSite(entries, name = "viasat.tv-live", icon="viasat.se.png")
            self._addSite(entries, name = "fc2.com-live",         icon="fc2.com.png")
            self._addSite(entries, name = "sky.com-live",         icon="sky.png")
            self._addSite(entries, name = "bbc.co.uk-live",       icon="bbc.png")
            self._addSite(entries, name = "nicovideo.jp-live",    icon="nicovideo.jp.png")

            self._addSite(entries, name = "nba.com", icon="nba.com.png")
            self._addSite(entries, name = "svt.se", icon="svt.se.png")
            self._addSite(entries, name = "viasat.tv", icon="viasat.se.png")
            self._addSite(entries, name = "tv4.se", icon="tv4.se.png")
            self._addSite(entries, name = "pacopacomama.com", icon="pacopacomama.com.png")
            self._addSite(entries, name = "redtube.com",icon="redtube.png")
            self._addSite(entries, name = "youku.com",icon="youku.com.png")
            self._addSite(entries, name = "brightcove.com",icon="brightcove.com.png")
            self._addSite(entries, name = "zdf.de",icon="zdf.de.png")
            self._addSite(entries, name = "ustream.tv",icon="ustream.tv.png")
            self._addSite(entries, name = "danpatrickshow.com",icon="danpatrickshow.com.png")
            self._addSite(entries, name = "ihoplive.com",icon="ihoplive.com.png")
            self._addSite(entries, name = "worldstarhiphop.com",icon="worldstarhiphop.com.png")
            self._addSite(entries, name = "msnbc.com",   icon="nbc.png")
            self._addSite(entries, name = "nbc.com",   icon="nbc.png")
            self._addSite(entries, name = "apple ios & apps",   icon="apple.apps.png")
            self._addSite(entries, name = "mediaset.it",   icon="medaiset.it.png")
            self._addSite(entries, name = "mediasetpremium.it",   icon="mediasetpremium.it.png")
            self._addSite(entries, name = "cubovision.it",   icon="cubovision.it.png")
            self._addSite(entries, name = "dmkt-sp.jp",   icon="dmkt-sp.jp.png")
            self._addSite(entries, name = "spankwire.com", icon="spankwire.com.png")
            self._addSite(entries, name = "keezmovies.com", icon="keezmovies.com.png")
            self._addSite(entries, name = "extremetube.com", icon="extremetube.com.png")
            self._addSite(entries, name = "rai.it", icon="rai.it.png")
            self._addSite(entries, name = "kataweb.it", icon="kataweb.it.png")
            self._addSite(entries, name = "phncdn.com",     icon="pornhub.png")
            self._addSite(entries, name = "interbusiness.it", icon="telecomitalia.com.png")
            self._addSite(entries, name = "usanetwork.com", icon="usanetwork.com.png")
            self._addSite(entries, name = "crackle.com", icon="crackle.com.png")
            self._addSite(entries, name = "dramafever.com", icon="dramafever.com.png")
            self._addSite(entries, name = "cnn.com", icon="cnn.com.png")
            self._addSite(entries, name = "cielotv.it", icon="cielotv.it.png")
            self._addSite(entries, name = "serviziopubblico.it", icon="serviziopubblico.it.png")
            self._addSite(entries, name = "realtimetv.it", icon="realtimetv.it.png")
            self._addSite(entries, name = "corriere.it", icon="corriere.it.png")
            self._addSite(entries, name = "cnn.com", icon="cnn.com.png")
            self._addSite(entries, name = "sky.it", icon="sky.png")
            self._addSite(entries, name = "sky.it-live", icon="sky.png")

            # version 4
            self._addSite(entries, name = "ted.com", icon="ted.com.png")
            self._addSite(entries, name = "ihopkc.org.com",icon="ihopkc.org.png")
            self._addSite(entries, name = "dmm.com",       icon="dmm.co.jp.png")
            self._addSite(entries, name = "esmas.com",       icon="esmas.com.png")
            self._addSite(entries, name = "tudou.com",       icon="tudou.com.png")
            self._addSite(entries, name = "pps.tv",       icon="pps.tv.png")
            self._addSite(entries, name = "google play apps",       icon="play.google.com.png")
            self._addSite(entries, name = "nba.com-live",       icon="nba.com.png")
            self._addSite(entries, name = "espn.com-live",       icon="espn.go.png")
            self._addSite(entries, name = "uefa.com-live",       icon="uefa.com.png")
            self._addSite(entries, name = "windows updates",       icon="updates.microsoft.com.png")
            self._addSite(entries, name = "pooq.co.kr",       icon="pooq.co.kr.png")
            self._addSite(entries, name = "naver.com",       icon="naver.com.png")
            self._addSite(entries, name = "clarin.com",       icon="clarin.com.png")
            self._addSite(entries, name = "ole.com.ar",       icon="ole.com.ar.png")
            self._addSite(entries, name = "globo.com",       icon="globo.com.png")
            self._addSite(entries, name = "ig.com.br",       icon="ig.com.br.com.png")
            self._addSite(entries, name = "dlatv.net",       icon="dlatv.net.png")
            self._addSite(entries, name = "uol.com.br",       icon="uol.com.br.png")
            self._addSite(entries, name = "terra.com.br",       icon="terra.com.br.png")
            self._addSite(entries, name = "terra.com",       icon="terra.com.png")
            self._addSite(entries, name = "abc.net.au",       icon="abc.net.au.png")
            self._addSite(entries, name = "rtve.es",       icon="rtve.es.png")
            self._addSite(entries, name = "telecinco.es",       icon="telecinco.es.png")
            self._addSite(entries, name = "abc.net.au",       icon="abc.net.au.png")
            self._addSite(entries, name = "rtve.es",       icon="rtve.es.png")
            self._addSite(entries, name = "telecinco.es",       icon="telecinco.es.png")
            self._addSite(entries, name = "eyny.com",           icon="eyny.com.png")
            # version 5
            self._addSite(entries, name = "channel4.com",    icon="c4assets.com.png")
            self._addSite(entries, name = "clip.vn",    icon="clip.vn.png")
            self._addSite(entries, name = "katsomo.fi",    icon="katsomo.fi.png")
            self._addSite(entries, name = "aenetworks.com",    icon="aenetworks.com.png")
            self._addSite(entries, name = "pgatour.com",    icon="pgatour.com.png")
            self._addSite(entries, name = "vnexpress.net",    icon="vnexpress.net.png")
            self._addSite(entries, name = "ninemsn.com.au",    icon="ninemsn.com.au.png")
            self._addSite(entries, name = "rutube.ru",    icon="rutube.ru.png")
            self._addSite(entries, name = "odnoklassniki.ru",    icon="odnoklassniki.ru.png")
            self._addSite(entries, name = "ivi.ru",    icon="ivi.ru.png")
            self._addSite(entries, name = "vkadre.ru",    icon="vkadre.ru.png")
            self._addSite(entries, name = "vimple.ru",    icon="vimple.ru.png")
            self._addSite(entries, name = "videomore.ru",    icon="videomore.ru.png")
            self._addSite(entries, name = "vesti.ru",    icon="vesti.ru.png")
            self._addSite(entries, name = "tv3.ru",    icon="tv3.ru.png")
            self._addSite(entries, name = "spruto.tv",    icon="spruto.tv.png")
            self._addSite(entries, name = "sibnet.ru",    icon="sibnet.ru.png")
            self._addSite(entries, name = "online-life.ru",    icon="online-life.ru.png")
            self._addSite(entries, name = "ntv.ru",    icon="ntv.ru.png")
            self._addSite(entries, name = "nowfilms.ru",    icon="nowfilms.ru.png")
            self._addSite(entries, name = "now.ru",    icon="now.ru.png")
            self._addSite(entries, name = "myvi.ru",    icon="myvi.ru.png")
            self._addSite(entries, name = "mir-druzey.ru",    icon="mir-druzey.ru.png")
            self._addSite(entries, name = "latino-serialo.ru",    icon="latino-serialo.ru.png")
            self._addSite(entries, name = "kinoylei.ru",    icon="kinoylei.ru.png")
            self._addSite(entries, name = "kinoylei.ru",    icon="kinoylei.ru.png")
            self._addSite(entries, name = "kinoxa-x.ru",    icon="kinoxa-x.ru.png")
            self._addSite(entries, name = "kinosolo.ru",    icon="kinosolo.ru.png")
            self._addSite(entries, name = "intv.ru",    icon="intv.ru.png")
            self._addSite(entries, name = "cn.ru",    icon="cn.ru.png")
            self._addSite(entries, name = "clipiki.ru",    icon="clipiki.ru.png")
            self._addSite(entries, name = "cdnvideo.ru",    icon="cdnvideo.ru.png")
            self._addSite(entries, name = "1tv.ru",    icon="1tv.ru.png")
            self._addSite(entries, name = "eyny.com",    icon="eyny.com.png")
            self._addSite(entries, name = "cokencorn.com",    icon="cokencorn.png")
            self._addSite(entries, name = "ooyala.com",    icon="ooyala.com.png")
            self._addSite(entries, name = "xyyp.mn",    icon="xyyp.mn.png")
            self._addSite(entries, name = "eyny.com",    icon="eyny.com.png")
            self._addSite(entries, name = "r7.com",    icon="r7.com.png")
            self._addSite(entries, name = "adap.tv",    icon="adap.tv.png")
            self._addSite(entries, name = "cox.net",    icon="cox.net.png")
            # 18042013 upload
            # manually added
            self._addSite(entries, name = "animepremium.tv", icon="animepremium.tv.png")
            self._addSite(entries, name = "castingcouchxmedia.com", icon="castingcouchxmedia.com.png")
            self._addSite(entries, name = "castup.net", icon="castup.net.png")
            self._addSite(entries, name = "dootvserver.com", icon="dootvserver.com.png")
            self._addSite(entries, name = "edgecastcdn.net", icon="edgecastcdn.net.png")
            self._addSite(entries, name = "filetrip.net", icon="filetrip.net.png")
            self._addSite(entries, name = "gachinco.com", icon="gachinco.com.png")
            self._addSite(entries, name = "global-cache.com", icon="global-cache.com.png")
            self._addSite(entries, name = "gogo.mn", icon="gogo.mn.png")
            self._addSite(entries, name = "homegrownfreaks.net", icon="homegrownfreaks.net.png")
            self._addSite(entries, name = "ip-only.net", icon="ip-only.net.png")
            self._addSite(entries, name = "letv.com.hk", icon="letv.com.hk.png")
            self._addSite(entries, name = "neulion.net", icon="neulion.net.png")
            self._addSite(entries, name = "passiontimes.hk", icon="passiontimes.hk.png")
            self._addSite(entries, name = "ppstv.com", icon="ppstv.com.png")
            self._addSite(entries, name = "serving-sys.com", icon="serving-sys.com.png")
            self._addSite(entries, name = "skycc.mn", icon="skycc.mn.png")
            self._addSite(entries, name = "telemundo.com", icon="telemundo.com.png")                              
            self._addSite(entries, name = "videoplaza.tv", icon="videoplaza.tv.png")
            self._addSite(entries, name = "warnerbros.com", icon="warnerbros.com.png")
            self._addSite(entries, name = "yam.com", icon="yam.com.png")
            self._addSite(entries, name = "vimeocdn.net",  icon="vimeo.png" )
            # favicons found by the script
            self._addSite(entries, name = "abc.net.au", icon="abc.net.au.png")
            self._addSite(entries, name = "abcnews.com", icon="abcnews.com.png")
            self._addSite(entries, name = "akamai.com", icon="akamai.com.png")
            self._addSite(entries, name = "amkino.com", icon="amkino.com.png")
            self._addSite(entries, name = "animax.mn", icon="animax.mn.png")
            self._addSite(entries, name = "asiamoviepass.eu", icon="asiamoviepass.eu.png")
            self._addSite(entries, name = "cliphunter.com", icon="cliphunter.com.png")
            self._addSite(entries, name = "cntv.cn", icon="cntv.cn.png")
            self._addSite(entries, name = "csports.se", icon="csports.se.png")
            self._addSite(entries, name = "eporner.com", icon="eporner.com.png")
            self._addSite(entries, name = "ero-video.net", icon="ero-video.net.png")
            self._addSite(entries, name = "freakshare.com", icon="freakshare.com.png")
            self._addSite(entries, name = "h0930.com", icon="h0930.com.png")
            self._addSite(entries, name = "heydouga.com", icon="heydouga.com.png")
            self._addSite(entries, name = "hkreporter.com", icon="hkreporter.com.png")
            self._addSite(entries, name = "imwx.com", icon="imwx.com.png")
            self._addSite(entries, name = "magnovideo.com", icon="magnovideo.com.png")
            self._addSite(entries, name = "masters.com", icon="masters.com.png")
            self._addSite(entries, name = "moevideo.net", icon="moevideo.net.png")
            self._addSite(entries, name = "movie-wave.com", icon="movie-wave.com.png")
            self._addSite(entries, name = "nbcnews.com", icon="nbcnews.com.png")
            self._addSite(entries, name = "netmovies.com.br", icon="netmovies.com.br.png")
            self._addSite(entries, name = "news.com.au", icon="news.com.au.png")
            self._addSite(entries, name = "nwciowa.edu", icon="nwciowa.edu.png")
            self._addSite(entries, name = "nxtv.jp", icon="nxtv.jp.png")
            self._addSite(entries, name = "pegmedia.org", icon="pegmedia.org.png")
            self._addSite(entries, name = "perfectgirls.net", icon="perfectgirls.net.png")
            self._addSite(entries, name = "porntube.com", icon="porntube.com.png")
            self._addSite(entries, name = "punyu.com", icon="punyu.com.png")
            self._addSite(entries, name = "redorbit.com", icon="redorbit.com.png")
            self._addSite(entries, name = "rtve.es", icon="rtve.es.png")
            self._addSite(entries, name = "s-premium.net", icon="s-premium.net.png")
            self._addSite(entries, name = "serviporno.com", icon="serviporno.com.png")
            self._addSite(entries, name = "shufuni.com", icon="shufuni.com.png")
            self._addSite(entries, name = "supermm.jp", icon="supermm.jp.png")
            self._addSite(entries, name = "theonion.com", icon="theonion.com.png")
            self._addSite(entries, name = "totalmovie.com", icon="totalmovie.com.png")
            self._addSite(entries, name = "tv.on.cc", icon="tv.on.cc.png")
            self._addSite(entries, name = "tv4play.se", icon="tv4play.se.png")
            self._addSite(entries, name = "tvb.com", icon="tvb.com.png")
            self._addSite(entries, name = "twitvid.com", icon="twitvid.com.png")
            self._addSite(entries, name = "univision.com", icon="univision.com.png")
            self._addSite(entries, name = "userporn.com", icon="userporn.com.png")
            self._addSite(entries, name = "ustvnow.com", icon="ustvnow.com.png")
            self._addSite(entries, name = "videobash.com", icon="videobash.com.png")
            self._addSite(entries, name = "videofun.me", icon="videofun.me.png")
            self._addSite(entries, name = "vivthomas.com", icon="vivthomas.com.png")
            self._addSite(entries, name = "vk.me", icon="vk.me.png")
            self._addSite(entries, name = "yaboon.com", icon="yaboon.com.png")
            self._addSite(entries, name = "yourlust.com", icon="yourlust.com.png")
            # Without script
            self._addSite(entries, name = "wat.tv", icon="wat.tv.png")
            self._addSite(entries, name = "tf1.fr", icon="tf1.fr.png")
            self._addSite(entries, name = "m6replay.fr", icon="m6replay.fr.png")
            self._addSite(entries, name = "news.com.au",    icon="news.com.au.png")
            self._addSite(entries, name = "vine.co",    icon="vine.co.png")

            result['entries'] = entries
        return result


