# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='include/a/infra/log/bits/destination.proto',
  package='a.log',
  serialized_pb='\n*include/a/infra/log/bits/destination.proto\x12\x05\x61.log\x1a\x1finclude/a/infra/log/level.proto\x1a\x30include/a/infra/log/bits/msg_dumper_config.proto\"g\n\x11\x44\x65stinationCfgGpb\x12\'\n\x08logLevel\x18\x01 \x01(\x0e\x32\x15.a.log.LevelGpb.Value\x12)\n\tdumperCfg\x18\x02 \x01(\x0b\x32\x16.a.log.MsgDumperCfgGpb\"f\n\x19\x44\x65stinationTextFileCfgGpb\x12\x30\n\x0eparentClassCfg\x18\x01 \x01(\x0b\x32\x18.a.log.DestinationCfgGpb\x12\x17\n\x0f\x66ileNamePattern\x18\x02 \x01(\t\"\xaa\x01\n\x18\x44\x65stinationGpbFileCfgGpb\x12\x30\n\x0eparentClassCfg\x18\x01 \x01(\x0b\x32\x18.a.log.DestinationCfgGpb\x12\x17\n\x0f\x66ileNamePattern\x18\x02 \x01(\t\x12\x12\n\nisRotating\x18\x03 \x01(\x08\x12\x19\n\x11rotationThreshold\x18\x04 \x01(\x03\x12\x14\n\x0cmaxTotalSize\x18\x05 \x01(\x03')




_DESTINATIONCFGGPB = descriptor.Descriptor(
  name='DestinationCfgGpb',
  full_name='a.log.DestinationCfgGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='logLevel', full_name='a.log.DestinationCfgGpb.logLevel', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dumperCfg', full_name='a.log.DestinationCfgGpb.dumperCfg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=136,
  serialized_end=239,
)


_DESTINATIONTEXTFILECFGGPB = descriptor.Descriptor(
  name='DestinationTextFileCfgGpb',
  full_name='a.log.DestinationTextFileCfgGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='parentClassCfg', full_name='a.log.DestinationTextFileCfgGpb.parentClassCfg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fileNamePattern', full_name='a.log.DestinationTextFileCfgGpb.fileNamePattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=241,
  serialized_end=343,
)


_DESTINATIONGPBFILECFGGPB = descriptor.Descriptor(
  name='DestinationGpbFileCfgGpb',
  full_name='a.log.DestinationGpbFileCfgGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='parentClassCfg', full_name='a.log.DestinationGpbFileCfgGpb.parentClassCfg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fileNamePattern', full_name='a.log.DestinationGpbFileCfgGpb.fileNamePattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isRotating', full_name='a.log.DestinationGpbFileCfgGpb.isRotating', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rotationThreshold', full_name='a.log.DestinationGpbFileCfgGpb.rotationThreshold', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='maxTotalSize', full_name='a.log.DestinationGpbFileCfgGpb.maxTotalSize', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=346,
  serialized_end=516,
)

import include.a.infra.log.level_pb2
import include.a.infra.log.bits.msg_dumper_config_pb2

_DESTINATIONCFGGPB.fields_by_name['logLevel'].enum_type = include.a.infra.log.level_pb2._LEVELGPB_VALUE
_DESTINATIONCFGGPB.fields_by_name['dumperCfg'].message_type = include.a.infra.log.bits.msg_dumper_config_pb2._MSGDUMPERCFGGPB
_DESTINATIONTEXTFILECFGGPB.fields_by_name['parentClassCfg'].message_type = _DESTINATIONCFGGPB
_DESTINATIONGPBFILECFGGPB.fields_by_name['parentClassCfg'].message_type = _DESTINATIONCFGGPB

class DestinationCfgGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DESTINATIONCFGGPB
  
  # @@protoc_insertion_point(class_scope:a.log.DestinationCfgGpb)

class DestinationTextFileCfgGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DESTINATIONTEXTFILECFGGPB
  
  # @@protoc_insertion_point(class_scope:a.log.DestinationTextFileCfgGpb)

class DestinationGpbFileCfgGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DESTINATIONGPBFILECFGGPB
  
  # @@protoc_insertion_point(class_scope:a.log.DestinationGpbFileCfgGpb)

# @@protoc_insertion_point(module_scope)
