/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojectui.Reports.ReqParamStatisticsReport;

import finalprojectui.Entities.Pair;
import finalprojectui.Utils.ComboTooltipRenderer;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author dell
 */
public class ReqParamStatisticsReportParamsPanel extends javax.swing.JPanel {
    private Vector<Pair<Integer,String>> _coalFiles;
    private ReqParamStatisticsReportReaultsPanel _resultsPanel;
    /**
     * Creates new form RequestsPercentagePerHeaderReportParametersPanel
     */
    public ReqParamStatisticsReportParamsPanel(ReqParamStatisticsReportReaultsPanel resultsPanel) {
        initComponents();
        _coalFiles=new Vector<Pair<Integer,String>>();
        _resultsPanel=resultsPanel;
    }

    /**
     * Creates new form RequestsPercentagePerHeaderReportParametersPanel
     */
    public ReqParamStatisticsReportParamsPanel(Vector<Pair<Integer,String>> coalFiles, ReqParamStatisticsReportReaultsPanel resultsPanel) {
        initComponents();
        _coalFiles=coalFiles;
        addCoalFilesToList(coalFiles);
        _resultsPanel=resultsPanel;
    }
    
    private void addCoalFilesToList(Vector<Pair<Integer,String>> lst)
    {
        for(Pair<Integer,String> pair : lst)
        {
            coalFilesCombo.addItem(pair.getValue());
        }
        coalFilesCombo.setRenderer(new ComboTooltipRenderer());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coalFilesCombo = new javax.swing.JComboBox();
        coalFilesLabel = new javax.swing.JLabel();
        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        ShowResultsLabel = new javax.swing.JLabel();
        showResultsCombo = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        coalFilesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));

        coalFilesLabel.setText("Coal files:");

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");

        ShowResultsLabel.setText("Show results as:");

        showResultsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Table", "Graph" }));
        showResultsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultsComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ShowResultsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showResultsCombo, 0, 150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coalFilesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coalFilesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loadButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coalFilesLabel)
                    .addComponent(coalFilesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowResultsLabel)
                    .addComponent(showResultsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(saveButton))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        if(showResultsCombo.getSelectedIndex()==0)
        {
            _resultsPanel.loadTable();
        }
        else
        {
            _resultsPanel.loadGraph();
        }
        
    }//GEN-LAST:event_loadButtonActionPerformed

    private void showResultsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultsComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showResultsComboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ShowResultsLabel;
    private javax.swing.JComboBox coalFilesCombo;
    private javax.swing.JLabel coalFilesLabel;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox showResultsCombo;
    // End of variables declaration//GEN-END:variables
}
