# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='include/a/infra/sm/zone.proto',
  package='a.sm',
  serialized_pb='\n\x1dinclude/a/infra/sm/zone.proto\x12\x04\x61.sm\"\xb2\x02\n\nZoneCfgGpb\x12\x11\n\ttotalSize\x18\x01 \x01(\x03\x12\x0e\n\x06zoneId\x18\x02 \x01(\x03\x12\x10\n\x08heapSize\x18\x03 \x01(\x03\x12\x17\n\x0fqueueUplinkSize\x18\x04 \x01(\x03\x12\x19\n\x11queueDownlinkSize\x18\x05 \x01(\x03\x12!\n\x19queueUplinkMaxMessageSize\x18\x06 \x01(\x03\x12#\n\x1bqueueDownlinkMaxMessageSize\x18\x07 \x01(\x03\x12-\n\x0bheapFsaData\x18\x08 \x03(\x0b\x32\x18.a.sm.ZoneCfgGpb.FsaData\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t\x1a/\n\x07\x46saData\x12\x11\n\tblockSize\x18\x01 \x01(\x03\x12\x11\n\tnumBlocks\x18\x02 \x01(\x03\"=\n\x0cZoneStateGpb\x12\r\n\x05shmId\x18\x01 \x01(\x03\x12\r\n\x05token\x18\x02 \x01(\x03\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\x03')




_ZONECFGGPB_FSADATA = descriptor.Descriptor(
  name='FsaData',
  full_name='a.sm.ZoneCfgGpb.FsaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='blockSize', full_name='a.sm.ZoneCfgGpb.FsaData.blockSize', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='numBlocks', full_name='a.sm.ZoneCfgGpb.FsaData.numBlocks', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=299,
  serialized_end=346,
)

_ZONECFGGPB = descriptor.Descriptor(
  name='ZoneCfgGpb',
  full_name='a.sm.ZoneCfgGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='totalSize', full_name='a.sm.ZoneCfgGpb.totalSize', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='zoneId', full_name='a.sm.ZoneCfgGpb.zoneId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='heapSize', full_name='a.sm.ZoneCfgGpb.heapSize', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='queueUplinkSize', full_name='a.sm.ZoneCfgGpb.queueUplinkSize', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='queueDownlinkSize', full_name='a.sm.ZoneCfgGpb.queueDownlinkSize', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='queueUplinkMaxMessageSize', full_name='a.sm.ZoneCfgGpb.queueUplinkMaxMessageSize', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='queueDownlinkMaxMessageSize', full_name='a.sm.ZoneCfgGpb.queueDownlinkMaxMessageSize', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='heapFsaData', full_name='a.sm.ZoneCfgGpb.heapFsaData', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='a.sm.ZoneCfgGpb.description', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ZONECFGGPB_FSADATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=346,
)


_ZONESTATEGPB = descriptor.Descriptor(
  name='ZoneStateGpb',
  full_name='a.sm.ZoneStateGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='shmId', full_name='a.sm.ZoneStateGpb.shmId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='token', full_name='a.sm.ZoneStateGpb.token', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='a.sm.ZoneStateGpb.address', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=348,
  serialized_end=409,
)


_ZONECFGGPB_FSADATA.containing_type = _ZONECFGGPB;
_ZONECFGGPB.fields_by_name['heapFsaData'].message_type = _ZONECFGGPB_FSADATA

class ZoneCfgGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class FsaData(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ZONECFGGPB_FSADATA
    
    # @@protoc_insertion_point(class_scope:a.sm.ZoneCfgGpb.FsaData)
  DESCRIPTOR = _ZONECFGGPB
  
  # @@protoc_insertion_point(class_scope:a.sm.ZoneCfgGpb)

class ZoneStateGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ZONESTATEGPB
  
  # @@protoc_insertion_point(class_scope:a.sm.ZoneStateGpb)

# @@protoc_insertion_point(module_scope)
