# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='sys/bdb/bdb_writer.proto',
  package='a.sys.bdb',
  serialized_pb='\n\x18sys/bdb/bdb_writer.proto\x12\ta.sys.bdb\x1a&include/a/infra/prov/definitions.proto\"L\n\x0f\x41ttachActionGpb\x12\x1b\n\x02in\x18\x01 \x01(\x0b\x32\x0f.a.prov.NullGpb\x12\x1c\n\x03out\x18\x02 \x01(\x0b\x32\x0f.a.prov.NullGpb\"2\n\x0fWriteMessageGpb\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\tgpb_chain\x18\x02 \x01(\x0c\"]\n\x15WriteMessageActionGpb\x12&\n\x02in\x18\x01 \x01(\x0b\x32\x1a.a.sys.bdb.WriteMessageGpb\x12\x1c\n\x03out\x18\x02 \x01(\x0b\x32\x0f.a.prov.NullGpb\"\x18\n\x08\x45raseGpb\x12\x0c\n\x04path\x18\x01 \x01(\t\"O\n\x0e\x45raseActionGpb\x12\x1f\n\x02in\x18\x01 \x01(\x0b\x32\x13.a.sys.bdb.EraseGpb\x12\x1c\n\x03out\x18\x02 \x01(\x0b\x32\x0f.a.prov.NullGpb')




_ATTACHACTIONGPB = descriptor.Descriptor(
  name='AttachActionGpb',
  full_name='a.sys.bdb.AttachActionGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='in', full_name='a.sys.bdb.AttachActionGpb.in', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='out', full_name='a.sys.bdb.AttachActionGpb.out', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=79,
  serialized_end=155,
)


_WRITEMESSAGEGPB = descriptor.Descriptor(
  name='WriteMessageGpb',
  full_name='a.sys.bdb.WriteMessageGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='path', full_name='a.sys.bdb.WriteMessageGpb.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gpb_chain', full_name='a.sys.bdb.WriteMessageGpb.gpb_chain', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=157,
  serialized_end=207,
)


_WRITEMESSAGEACTIONGPB = descriptor.Descriptor(
  name='WriteMessageActionGpb',
  full_name='a.sys.bdb.WriteMessageActionGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='in', full_name='a.sys.bdb.WriteMessageActionGpb.in', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='out', full_name='a.sys.bdb.WriteMessageActionGpb.out', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=209,
  serialized_end=302,
)


_ERASEGPB = descriptor.Descriptor(
  name='EraseGpb',
  full_name='a.sys.bdb.EraseGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='path', full_name='a.sys.bdb.EraseGpb.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=304,
  serialized_end=328,
)


_ERASEACTIONGPB = descriptor.Descriptor(
  name='EraseActionGpb',
  full_name='a.sys.bdb.EraseActionGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='in', full_name='a.sys.bdb.EraseActionGpb.in', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='out', full_name='a.sys.bdb.EraseActionGpb.out', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=330,
  serialized_end=409,
)

import include.a.infra.prov.definitions_pb2

_ATTACHACTIONGPB.fields_by_name['in'].message_type = include.a.infra.prov.definitions_pb2._NULLGPB
_ATTACHACTIONGPB.fields_by_name['out'].message_type = include.a.infra.prov.definitions_pb2._NULLGPB
_WRITEMESSAGEACTIONGPB.fields_by_name['in'].message_type = _WRITEMESSAGEGPB
_WRITEMESSAGEACTIONGPB.fields_by_name['out'].message_type = include.a.infra.prov.definitions_pb2._NULLGPB
_ERASEACTIONGPB.fields_by_name['in'].message_type = _ERASEGPB
_ERASEACTIONGPB.fields_by_name['out'].message_type = include.a.infra.prov.definitions_pb2._NULLGPB

class AttachActionGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ATTACHACTIONGPB
  
  # @@protoc_insertion_point(class_scope:a.sys.bdb.AttachActionGpb)

class WriteMessageGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WRITEMESSAGEGPB
  
  # @@protoc_insertion_point(class_scope:a.sys.bdb.WriteMessageGpb)

class WriteMessageActionGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WRITEMESSAGEACTIONGPB
  
  # @@protoc_insertion_point(class_scope:a.sys.bdb.WriteMessageActionGpb)

class EraseGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ERASEGPB
  
  # @@protoc_insertion_point(class_scope:a.sys.bdb.EraseGpb)

class EraseActionGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ERASEACTIONGPB
  
  # @@protoc_insertion_point(class_scope:a.sys.bdb.EraseActionGpb)

# @@protoc_insertion_point(module_scope)
