# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='include/a/infra/net/util/mac_address.proto',
  package='a.net.util',
  serialized_pb='\n*include/a/infra/net/util/mac_address.proto\x12\na.net.util\"0\n\rmacAddressGpb\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tbytearray\x18\x02 \x01(\x0c')




_MACADDRESSGPB = descriptor.Descriptor(
  name='macAddressGpb',
  full_name='a.net.util.macAddressGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='a.net.util.macAddressGpb.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bytearray', full_name='a.net.util.macAddressGpb.bytearray', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=106,
)



class macAddressGpb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MACADDRESSGPB
  
  # @@protoc_insertion_point(class_scope:a.net.util.macAddressGpb)

# @@protoc_insertion_point(module_scope)
